/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SCntFlexyViewIslamPromoAboutMe, } from "./components/cnt-flexy-view-islam-promo-about-me/res/view/cnt-flexy-view-islam-promo-about-me/interface/common.interface";
import { SCntFlexyViewIslamPromoAffordable, } from "./components/cnt-flexy-view-islam-promo-affordable/res/view/cnt-flexy-view-islam-promo-affordable/interface/common.interface";
import { SCntFlexyViewIslamPromoCommunication, } from "./components/cnt-flexy-view-islam-promo-communication/res/view/cnt-flexy-view-islam-promo-communication/interface/common.interface";
import { SCntFlexyViewIslamPromoHeader, } from "./components/cnt-flexy-view-islam-promo-header/res/view/cnt-flexy-view-islam-promo-header/interface/common.interface";
import { SCntFlexyViewIslamPromoOpportunity, } from "./components/cnt-flexy-view-islam-promo-opportunities/res/view/cnt-flexy-view-islam-promo-opportunities/interface/common.interface";
import { SCntFlexyViewIslamPromoQuality, } from "./components/cnt-flexy-view-islam-promo-quality/res/view/cnt-flexy-view-islam-promo-quality/interface/common.interface";
import { SCntFlexyViewIslamPromoSkills, } from "./components/cnt-flexy-view-islam-promo-skills/res/view/cnt-flexy-view-islam-promo-skills/interface/common.interface";
import { SCntFlexyViewIslamPromoWorks, } from "./components/cnt-flexy-view-islam-promo-works/res/view/cnt-flexy-view-islam-promo-works/interface/common.interface";
export namespace Components {
    interface CntFlexyViewIslamPromoAboutMe {
        /**
          * Приём данных из массива для вывода
         */
        "intro": SCntFlexyViewIslamPromoAboutMe[];
        "payload": any;
    }
    interface CntFlexyViewIslamPromoAboutMe1_01 {
        "pathToAssets": any;
        "payload": any;
    }
    interface CntFlexyViewIslamPromoAffordable {
        /**
          * Приём данных из массива для вывода
         */
        "intro": SCntFlexyViewIslamPromoAffordable[];
        "payload": any;
    }
    interface CntFlexyViewIslamPromoAffordable1_01 {
        "pathToAssets": any;
        "payload": any;
    }
    interface CntFlexyViewIslamPromoCommunication {
        /**
          * Приём данных из массива для вывода
         */
        "intro": SCntFlexyViewIslamPromoCommunication[];
        /**
          * Данные компонента CntFlexyViewIslamPromoCommunication
         */
        "payload": any;
    }
    interface CntFlexyViewIslamPromoCommunication1_01 {
        "payload": any;
    }
    interface CntFlexyViewIslamPromoFooter {
        "payload": any;
    }
    interface CntFlexyViewIslamPromoFooter1_01 {
        "payload": any;
    }
    interface CntFlexyViewIslamPromoHeader {
        /**
          * Приём данных из массива для вывода
         */
        "intro": SCntFlexyViewIslamPromoHeader[];
        "payload": any;
    }
    interface CntFlexyViewIslamPromoHeader1_01 {
        "payload": any;
    }
    interface CntFlexyViewIslamPromoOpportunities {
        /**
          * Приём данных из массива для вывода
         */
        "intro": SCntFlexyViewIslamPromoOpportunity[];
        "payload": any;
    }
    interface CntFlexyViewIslamPromoOpportunities1_01 {
        "payload": any;
    }
    interface CntFlexyViewIslamPromoQuality {
        /**
          * Приём данных из массива для вывода
         */
        "intro": SCntFlexyViewIslamPromoQuality[];
        "payload": any;
    }
    interface CntFlexyViewIslamPromoQuality1_01 {
        "payload": any;
    }
    interface CntFlexyViewIslamPromoSkills {
        /**
          * Приём данных из массива для вывода
         */
        "intro": SCntFlexyViewIslamPromoSkills[];
        "payload": any;
    }
    interface CntFlexyViewIslamPromoSkills1_01 {
        "pathToAssets": any;
        "payload": any;
    }
    interface CntFlexyViewIslamPromoWorks {
        /**
          * Приём данных из массива для вывода
         */
        "intro": SCntFlexyViewIslamPromoWorks[];
        "payload": any;
    }
    interface CntFlexyViewIslamPromoWorks1_01 {
        "pathToAssets": any;
        "payload": any;
    }
    interface MyComponent {
    }
}
declare global {
    interface HTMLCntFlexyViewIslamPromoAboutMeElement extends Components.CntFlexyViewIslamPromoAboutMe, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamPromoAboutMeElement: {
        prototype: HTMLCntFlexyViewIslamPromoAboutMeElement;
        new (): HTMLCntFlexyViewIslamPromoAboutMeElement;
    };
    interface HTMLCntFlexyViewIslamPromoAboutMe1_01Element extends Components.CntFlexyViewIslamPromoAboutMe1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamPromoAboutMe1_01Element: {
        prototype: HTMLCntFlexyViewIslamPromoAboutMe1_01Element;
        new (): HTMLCntFlexyViewIslamPromoAboutMe1_01Element;
    };
    interface HTMLCntFlexyViewIslamPromoAffordableElement extends Components.CntFlexyViewIslamPromoAffordable, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamPromoAffordableElement: {
        prototype: HTMLCntFlexyViewIslamPromoAffordableElement;
        new (): HTMLCntFlexyViewIslamPromoAffordableElement;
    };
    interface HTMLCntFlexyViewIslamPromoAffordable1_01Element extends Components.CntFlexyViewIslamPromoAffordable1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamPromoAffordable1_01Element: {
        prototype: HTMLCntFlexyViewIslamPromoAffordable1_01Element;
        new (): HTMLCntFlexyViewIslamPromoAffordable1_01Element;
    };
    interface HTMLCntFlexyViewIslamPromoCommunicationElement extends Components.CntFlexyViewIslamPromoCommunication, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamPromoCommunicationElement: {
        prototype: HTMLCntFlexyViewIslamPromoCommunicationElement;
        new (): HTMLCntFlexyViewIslamPromoCommunicationElement;
    };
    interface HTMLCntFlexyViewIslamPromoCommunication1_01Element extends Components.CntFlexyViewIslamPromoCommunication1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamPromoCommunication1_01Element: {
        prototype: HTMLCntFlexyViewIslamPromoCommunication1_01Element;
        new (): HTMLCntFlexyViewIslamPromoCommunication1_01Element;
    };
    interface HTMLCntFlexyViewIslamPromoFooterElement extends Components.CntFlexyViewIslamPromoFooter, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamPromoFooterElement: {
        prototype: HTMLCntFlexyViewIslamPromoFooterElement;
        new (): HTMLCntFlexyViewIslamPromoFooterElement;
    };
    interface HTMLCntFlexyViewIslamPromoFooter1_01Element extends Components.CntFlexyViewIslamPromoFooter1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamPromoFooter1_01Element: {
        prototype: HTMLCntFlexyViewIslamPromoFooter1_01Element;
        new (): HTMLCntFlexyViewIslamPromoFooter1_01Element;
    };
    interface HTMLCntFlexyViewIslamPromoHeaderElement extends Components.CntFlexyViewIslamPromoHeader, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamPromoHeaderElement: {
        prototype: HTMLCntFlexyViewIslamPromoHeaderElement;
        new (): HTMLCntFlexyViewIslamPromoHeaderElement;
    };
    interface HTMLCntFlexyViewIslamPromoHeader1_01Element extends Components.CntFlexyViewIslamPromoHeader1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamPromoHeader1_01Element: {
        prototype: HTMLCntFlexyViewIslamPromoHeader1_01Element;
        new (): HTMLCntFlexyViewIslamPromoHeader1_01Element;
    };
    interface HTMLCntFlexyViewIslamPromoOpportunitiesElement extends Components.CntFlexyViewIslamPromoOpportunities, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamPromoOpportunitiesElement: {
        prototype: HTMLCntFlexyViewIslamPromoOpportunitiesElement;
        new (): HTMLCntFlexyViewIslamPromoOpportunitiesElement;
    };
    interface HTMLCntFlexyViewIslamPromoOpportunities1_01Element extends Components.CntFlexyViewIslamPromoOpportunities1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamPromoOpportunities1_01Element: {
        prototype: HTMLCntFlexyViewIslamPromoOpportunities1_01Element;
        new (): HTMLCntFlexyViewIslamPromoOpportunities1_01Element;
    };
    interface HTMLCntFlexyViewIslamPromoQualityElement extends Components.CntFlexyViewIslamPromoQuality, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamPromoQualityElement: {
        prototype: HTMLCntFlexyViewIslamPromoQualityElement;
        new (): HTMLCntFlexyViewIslamPromoQualityElement;
    };
    interface HTMLCntFlexyViewIslamPromoQuality1_01Element extends Components.CntFlexyViewIslamPromoQuality1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamPromoQuality1_01Element: {
        prototype: HTMLCntFlexyViewIslamPromoQuality1_01Element;
        new (): HTMLCntFlexyViewIslamPromoQuality1_01Element;
    };
    interface HTMLCntFlexyViewIslamPromoSkillsElement extends Components.CntFlexyViewIslamPromoSkills, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamPromoSkillsElement: {
        prototype: HTMLCntFlexyViewIslamPromoSkillsElement;
        new (): HTMLCntFlexyViewIslamPromoSkillsElement;
    };
    interface HTMLCntFlexyViewIslamPromoSkills1_01Element extends Components.CntFlexyViewIslamPromoSkills1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamPromoSkills1_01Element: {
        prototype: HTMLCntFlexyViewIslamPromoSkills1_01Element;
        new (): HTMLCntFlexyViewIslamPromoSkills1_01Element;
    };
    interface HTMLCntFlexyViewIslamPromoWorksElement extends Components.CntFlexyViewIslamPromoWorks, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamPromoWorksElement: {
        prototype: HTMLCntFlexyViewIslamPromoWorksElement;
        new (): HTMLCntFlexyViewIslamPromoWorksElement;
    };
    interface HTMLCntFlexyViewIslamPromoWorks1_01Element extends Components.CntFlexyViewIslamPromoWorks1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamPromoWorks1_01Element: {
        prototype: HTMLCntFlexyViewIslamPromoWorks1_01Element;
        new (): HTMLCntFlexyViewIslamPromoWorks1_01Element;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "cnt-flexy-view-islam-promo-about-me": HTMLCntFlexyViewIslamPromoAboutMeElement;
        "cnt-flexy-view-islam-promo-about-me-1_01": HTMLCntFlexyViewIslamPromoAboutMe1_01Element;
        "cnt-flexy-view-islam-promo-affordable": HTMLCntFlexyViewIslamPromoAffordableElement;
        "cnt-flexy-view-islam-promo-affordable-1_01": HTMLCntFlexyViewIslamPromoAffordable1_01Element;
        "cnt-flexy-view-islam-promo-communication": HTMLCntFlexyViewIslamPromoCommunicationElement;
        "cnt-flexy-view-islam-promo-communication-1_01": HTMLCntFlexyViewIslamPromoCommunication1_01Element;
        "cnt-flexy-view-islam-promo-footer": HTMLCntFlexyViewIslamPromoFooterElement;
        "cnt-flexy-view-islam-promo-footer-1_01": HTMLCntFlexyViewIslamPromoFooter1_01Element;
        "cnt-flexy-view-islam-promo-header": HTMLCntFlexyViewIslamPromoHeaderElement;
        "cnt-flexy-view-islam-promo-header-1_01": HTMLCntFlexyViewIslamPromoHeader1_01Element;
        "cnt-flexy-view-islam-promo-opportunities": HTMLCntFlexyViewIslamPromoOpportunitiesElement;
        "cnt-flexy-view-islam-promo-opportunities-1_01": HTMLCntFlexyViewIslamPromoOpportunities1_01Element;
        "cnt-flexy-view-islam-promo-quality": HTMLCntFlexyViewIslamPromoQualityElement;
        "cnt-flexy-view-islam-promo-quality-1_01": HTMLCntFlexyViewIslamPromoQuality1_01Element;
        "cnt-flexy-view-islam-promo-skills": HTMLCntFlexyViewIslamPromoSkillsElement;
        "cnt-flexy-view-islam-promo-skills-1_01": HTMLCntFlexyViewIslamPromoSkills1_01Element;
        "cnt-flexy-view-islam-promo-works": HTMLCntFlexyViewIslamPromoWorksElement;
        "cnt-flexy-view-islam-promo-works-1_01": HTMLCntFlexyViewIslamPromoWorks1_01Element;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface CntFlexyViewIslamPromoAboutMe {
        /**
          * Приём данных из массива для вывода
         */
        "intro"?: SCntFlexyViewIslamPromoAboutMe[];
        /**
          * Клик по Кнопке
         */
        "onClickAboutMeButton"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Заголовку
         */
        "onClickAboutMeHeading"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Картинке
         */
        "onClickAboutMeImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Подписи
         */
        "onClickAboutMeSignature"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Тексту
         */
        "onClickAboutMeText"?: (event: CustomEvent<any>) => void;
        "payload"?: any;
    }
    interface CntFlexyViewIslamPromoAboutMe1_01 {
        "pathToAssets"?: any;
        "payload"?: any;
    }
    interface CntFlexyViewIslamPromoAffordable {
        /**
          * Приём данных из массива для вывода
         */
        "intro"?: SCntFlexyViewIslamPromoAffordable[];
        /**
          * Клик по Кнопке
         */
        "onClickAffordableButton"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Заголовку
         */
        "onClickAffordableHeading"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Под заголовку
         */
        "onClickAffordableName"?: (event: CustomEvent<any>) => void;
        "payload"?: any;
    }
    interface CntFlexyViewIslamPromoAffordable1_01 {
        "pathToAssets"?: any;
        "payload"?: any;
    }
    interface CntFlexyViewIslamPromoCommunication {
        /**
          * Приём данных из массива для вывода
         */
        "intro"?: SCntFlexyViewIslamPromoCommunication[];
        /**
          * Клик по FacebookIcon
         */
        "onClickCommunicationFacebookIcon"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по InstagramIcon
         */
        "onClickCommunicationInstagramIcon"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по почте
         */
        "onClickCommunicationLetter"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по LetterIcon
         */
        "onClickCommunicationLetterIcon"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по LinkedinIcon
         */
        "onClickCommunicationLinkedinIcon"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по адресу
         */
        "onClickCommunicationLocation"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по MapMarker
         */
        "onClickCommunicationMapMarker"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по номеру
         */
        "onClickCommunicationPhone"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по PhoneIcon
         */
        "onClickCommunicationPhoneIcon"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по TwitterIcon
         */
        "onClickCommunicationTwitterIcon"?: (event: CustomEvent<any>) => void;
        /**
          * Данные компонента CntFlexyViewIslamPromoCommunication
         */
        "payload"?: any;
    }
    interface CntFlexyViewIslamPromoCommunication1_01 {
        "payload"?: any;
    }
    interface CntFlexyViewIslamPromoFooter {
        "payload"?: any;
    }
    interface CntFlexyViewIslamPromoFooter1_01 {
        "payload"?: any;
    }
    interface CntFlexyViewIslamPromoHeader {
        /**
          * Приём данных из массива для вывода
         */
        "intro"?: SCntFlexyViewIslamPromoHeader[];
        /**
          * Клик по AboutUs
         */
        "onClickHeaderAboutUsNav"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Contacts
         */
        "onClickHeaderContactsNav"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по developer
         */
        "onClickHeaderDeveloper"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Home
         */
        "onClickHeaderHomeNav"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по MaleIcon
         */
        "onClickHeaderMaleIcon"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по OurTeam
         */
        "onClickHeaderOurTeamNav"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по PracticeAreas
         */
        "onClickHeaderPracticeAreasNav"?: (event: CustomEvent<any>) => void;
        "payload"?: any;
    }
    interface CntFlexyViewIslamPromoHeader1_01 {
        "payload"?: any;
    }
    interface CntFlexyViewIslamPromoOpportunities {
        /**
          * Приём данных из массива для вывода
         */
        "intro"?: SCntFlexyViewIslamPromoOpportunity[];
        /**
          * Клик по Второй иконке
         */
        "onClickOpportunitiesCogIcon"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Второму тексту
         */
        "onClickOpportunitiesCogText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Второму под заголовку
         */
        "onClickOpportunitiesCogTitle"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Первой иконке
         */
        "onClickOpportunitiesComputerIcon"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Первому тексту
         */
        "onClickOpportunitiesComputerText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Первому под заголовку
         */
        "onClickOpportunitiesComputerTitle"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Заголовку
         */
        "onClickOpportunitiesHeading"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Третьей иконке
         */
        "onClickOpportunitiesPictureIcon"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Третьму тексту
         */
        "onClickOpportunitiesPictureText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Третьему под заголовку
         */
        "onClickOpportunitiesPictureTitle"?: (event: CustomEvent<any>) => void;
        "payload"?: any;
    }
    interface CntFlexyViewIslamPromoOpportunities1_01 {
        "payload"?: any;
    }
    interface CntFlexyViewIslamPromoQuality {
        /**
          * Приём данных из массива для вывода
         */
        "intro"?: SCntFlexyViewIslamPromoQuality[];
        /**
          * Клик по Заголовку
         */
        "onClickQualityHeading"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Иконке
         */
        "onClickQualityIcon"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по тексту
         */
        "onClickQualityText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Заголовку
         */
        "onClickQualityTitle"?: (event: CustomEvent<any>) => void;
        "payload"?: any;
    }
    interface CntFlexyViewIslamPromoQuality1_01 {
        "payload"?: any;
    }
    interface CntFlexyViewIslamPromoSkills {
        /**
          * Приём данных из массива для вывода
         */
        "intro"?: SCntFlexyViewIslamPromoSkills[];
        /**
          * Клик по Картинке Angular
         */
        "onClickSkillsAngularImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Тексту Angular
         */
        "onClickSkillsAngularText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Картинке Bootstrap
         */
        "onClickSkillsBootstrapImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Тексту Bootstrap
         */
        "onClickSkillsBootstrapText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Картинке Css
         */
        "onClickSkillsCssImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Тексту Css
         */
        "onClickSkillsCssText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Заголовку
         */
        "onClickSkillsHeading"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по  Картинке Html
         */
        "onClickSkillsHtmlImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Тексту Html
         */
        "onClickSkillsHtmlText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Картинке Js
         */
        "onClickSkillsJsImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Тексту Js
         */
        "onClickSkillsJsText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Картинке React
         */
        "onClickSkillsReactImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Тексту React
         */
        "onClickSkillsReactText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Картинке Stencil
         */
        "onClickSkillsStencilImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Тексту Stencil
         */
        "onClickSkillsStencilText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Картинке WordPress
         */
        "onClickSkillsWpImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Тексту WordPress
         */
        "onClickSkillsWpText"?: (event: CustomEvent<any>) => void;
        "payload"?: any;
    }
    interface CntFlexyViewIslamPromoSkills1_01 {
        "pathToAssets"?: any;
        "payload"?: any;
    }
    interface CntFlexyViewIslamPromoWorks {
        /**
          * Приём данных из массива для вывода
         */
        "intro"?: SCntFlexyViewIslamPromoWorks[];
        /**
          * Клик по Кнопке
         */
        "onClickWorksButton"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Заголовку
         */
        "onClickWorksHeading"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по первой картинке
         */
        "onClickWorksShopImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по тексту
         */
        "onClickWorksShopText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по второй картинке
         */
        "onClickWorksWorkImage1"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по третьей картинке
         */
        "onClickWorksWorkImage2"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по тексту
         */
        "onClickWorksWorkText1"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по тексту
         */
        "onClickWorksWorkText2"?: (event: CustomEvent<any>) => void;
        "payload"?: any;
    }
    interface CntFlexyViewIslamPromoWorks1_01 {
        "pathToAssets"?: any;
        "payload"?: any;
    }
    interface MyComponent {
    }
    interface IntrinsicElements {
        "cnt-flexy-view-islam-promo-about-me": CntFlexyViewIslamPromoAboutMe;
        "cnt-flexy-view-islam-promo-about-me-1_01": CntFlexyViewIslamPromoAboutMe1_01;
        "cnt-flexy-view-islam-promo-affordable": CntFlexyViewIslamPromoAffordable;
        "cnt-flexy-view-islam-promo-affordable-1_01": CntFlexyViewIslamPromoAffordable1_01;
        "cnt-flexy-view-islam-promo-communication": CntFlexyViewIslamPromoCommunication;
        "cnt-flexy-view-islam-promo-communication-1_01": CntFlexyViewIslamPromoCommunication1_01;
        "cnt-flexy-view-islam-promo-footer": CntFlexyViewIslamPromoFooter;
        "cnt-flexy-view-islam-promo-footer-1_01": CntFlexyViewIslamPromoFooter1_01;
        "cnt-flexy-view-islam-promo-header": CntFlexyViewIslamPromoHeader;
        "cnt-flexy-view-islam-promo-header-1_01": CntFlexyViewIslamPromoHeader1_01;
        "cnt-flexy-view-islam-promo-opportunities": CntFlexyViewIslamPromoOpportunities;
        "cnt-flexy-view-islam-promo-opportunities-1_01": CntFlexyViewIslamPromoOpportunities1_01;
        "cnt-flexy-view-islam-promo-quality": CntFlexyViewIslamPromoQuality;
        "cnt-flexy-view-islam-promo-quality-1_01": CntFlexyViewIslamPromoQuality1_01;
        "cnt-flexy-view-islam-promo-skills": CntFlexyViewIslamPromoSkills;
        "cnt-flexy-view-islam-promo-skills-1_01": CntFlexyViewIslamPromoSkills1_01;
        "cnt-flexy-view-islam-promo-works": CntFlexyViewIslamPromoWorks;
        "cnt-flexy-view-islam-promo-works-1_01": CntFlexyViewIslamPromoWorks1_01;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cnt-flexy-view-islam-promo-about-me": LocalJSX.CntFlexyViewIslamPromoAboutMe & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamPromoAboutMeElement>;
            "cnt-flexy-view-islam-promo-about-me-1_01": LocalJSX.CntFlexyViewIslamPromoAboutMe1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamPromoAboutMe1_01Element>;
            "cnt-flexy-view-islam-promo-affordable": LocalJSX.CntFlexyViewIslamPromoAffordable & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamPromoAffordableElement>;
            "cnt-flexy-view-islam-promo-affordable-1_01": LocalJSX.CntFlexyViewIslamPromoAffordable1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamPromoAffordable1_01Element>;
            "cnt-flexy-view-islam-promo-communication": LocalJSX.CntFlexyViewIslamPromoCommunication & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamPromoCommunicationElement>;
            "cnt-flexy-view-islam-promo-communication-1_01": LocalJSX.CntFlexyViewIslamPromoCommunication1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamPromoCommunication1_01Element>;
            "cnt-flexy-view-islam-promo-footer": LocalJSX.CntFlexyViewIslamPromoFooter & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamPromoFooterElement>;
            "cnt-flexy-view-islam-promo-footer-1_01": LocalJSX.CntFlexyViewIslamPromoFooter1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamPromoFooter1_01Element>;
            "cnt-flexy-view-islam-promo-header": LocalJSX.CntFlexyViewIslamPromoHeader & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamPromoHeaderElement>;
            "cnt-flexy-view-islam-promo-header-1_01": LocalJSX.CntFlexyViewIslamPromoHeader1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamPromoHeader1_01Element>;
            "cnt-flexy-view-islam-promo-opportunities": LocalJSX.CntFlexyViewIslamPromoOpportunities & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamPromoOpportunitiesElement>;
            "cnt-flexy-view-islam-promo-opportunities-1_01": LocalJSX.CntFlexyViewIslamPromoOpportunities1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamPromoOpportunities1_01Element>;
            "cnt-flexy-view-islam-promo-quality": LocalJSX.CntFlexyViewIslamPromoQuality & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamPromoQualityElement>;
            "cnt-flexy-view-islam-promo-quality-1_01": LocalJSX.CntFlexyViewIslamPromoQuality1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamPromoQuality1_01Element>;
            "cnt-flexy-view-islam-promo-skills": LocalJSX.CntFlexyViewIslamPromoSkills & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamPromoSkillsElement>;
            "cnt-flexy-view-islam-promo-skills-1_01": LocalJSX.CntFlexyViewIslamPromoSkills1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamPromoSkills1_01Element>;
            "cnt-flexy-view-islam-promo-works": LocalJSX.CntFlexyViewIslamPromoWorks & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamPromoWorksElement>;
            "cnt-flexy-view-islam-promo-works-1_01": LocalJSX.CntFlexyViewIslamPromoWorks1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamPromoWorks1_01Element>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
